name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v4.2.2
        

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: cantuariac/fake-shop-devops-cloud:v1
  
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
