name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v4.2.2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            cantuariac/fake-shop-devops-cloud:v${{ github.run_number }}
            cantuariac/fake-shop-devops-cloud:latest
  
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v4.2.2
      
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KS8_KUBECONFIG }}
      
      - uses: Azure/k8s-deploy@v5
        with:
            manifests: |
              k8s/deployment.yaml
            images: |
              cantuariac/fake-shop-devops-cloud:v${{ github.run_number }}
